server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    charset utf-8;

    location = /robots.txt {
        try_files $uri =404;
        default_type text/plain;
    }

    location = /sitemap.xml {
        try_files $uri =404;
        default_type application/xml;
    }

    location = /index_backup_antes_home_comercial.html {
        return 410;
    }

    location = /index_home_comercial_preview.html {
        return 410;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~\.(?:jpg|jpeg|gif|png|ico|css|js|pdf|txt|woff2|svg|woff|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}

server {
    listen 80;
    server_name funerarias.iagentsdigital.com;
    root /usr/share/nginx/html;
    index funerarias.html;

    charset utf-8;

    location / {
        try_files $uri $uri/ /funerarias.html;
    }
}

server {
    listen 80;
    server_name costera.iagentsdigital.com;
    root /usr/share/nginx/html;
    index landing-captacion-costera.html;

    charset utf-8;

    location / {
        try_files $uri $uri/ /landing-captacion-costera.html;
    }
}

server {
    listen 80;
    server_name valoracion.iagentsdigital.com;
    root /usr/share/nginx/html;
    index valoracion.html;

    charset utf-8;

    location / {
        try_files $uri $uri/ /valoracion.html;
    }
}
