server {
    escuchar    80;
    nombre_del_servidor  host local;
    raíz         /var/share/nginx/html;
    índice       index.html;

    conjunto_de_caracteres utf-8;

    ubicación / {
        archivos_de_intento $uri $uri/ /index.html;
    }

    ubicación ~\.(?:jpg|jpeg|gif|png|ico|css|js|pdf|txt|woff2|svg|woff|ttf|eot)$ {
        expira 30 días;
        agregar_encabezado Control de caché "público, sin transformación";
    }
}

server {
    escuchar    80;
    nombre_del_servidor  costera.iagentsdigital.com;
    raíz         /var/share/nginx/html;
    índice       landing-captacion-costera.html;

    conjunto_de_caracteres utf-8;

    ubicación / {
        archivos_de_intento $uri $uri/ /landing-captacion-costera.html;
    }
}
